BEGIN;
CREATE SCHEMA IF NOT EXISTS public;
DROP TABLE IF EXISTS "budget_master" CASCADE;
CREATE TABLE "budget_master" (
  "id" BIGSERIAL PRIMARY KEY,
    "source_id" TEXT,
"route_id_site_id" TEXT,
  "ce_length_mtr" TEXT,
  "ri_cost_per_meter" TEXT,
  "material_cost_per_meter" TEXT,
  "build_cost_per_meter" TEXT,
  "total_ri_amount" TEXT,
  "material_cost" TEXT,
  "execution_cost_including_hh" TEXT,
  "total_cost_without_deposit" TEXT,
  "route_type" TEXT,
  "build_type" TEXT,
  "category_type" TEXT
);
DROP TABLE IF EXISTS "dn_master" CASCADE;
CREATE TABLE "dn_master" (
  "id" BIGSERIAL PRIMARY KEY,
  "sr_no" TEXT,
  "route_type" TEXT,
  "ip1_co_built" TEXT,
  "dn_recipient" TEXT,
  "project_name" TEXT,
  "route_id_site_id" TEXT,
  "uid" TEXT,
  "build_type" TEXT,
  "category_type" TEXT,
  "survey_id" TEXT,
  "po_number" TEXT,
  "po_length" TEXT,
  "parent_route" TEXT,
  "ce_route_lmc_id" TEXT,
  "route_lmc_section_id" TEXT,
  "route_lmc_subsection_id" TEXT,
  "application_number" TEXT,
  "application_length_mtr" TEXT,
  "application_date" TEXT,
  "from_location" TEXT,
  "to_location" TEXT,
  "authority" TEXT,
  "ward" TEXT,
  "dn_number" TEXT,
  "dn_length_mtr" TEXT,
  "dn_received_date" TEXT,
  "trench_type" TEXT,
  "ot_length" TEXT,
  "surface" TEXT,
  "surface_wise_ri_amount" TEXT,
  "dn_ri_amount" TEXT,
  "surface_wise_multiplication_factor" TEXT,
  "ground_rent" TEXT,
  "administrative_charge" TEXT,
  "supervision_charges" TEXT,
  "chamber_fee" TEXT,
  "gst" TEXT,
  "ri_budget_amount_per_meter" TEXT,
  "projected_budget_ri_amount_dn" TEXT,
  "actual_total_non_refundable" TEXT,
  "non_refundable_amount_per_mtr" TEXT,
  "proj_non_refundable_savings_per_mtr" TEXT,
  "deposit" TEXT,
  "total_dn_amount" TEXT,
  "new_revised_dn_number" TEXT,
  "new_revised_dn_against" TEXT,
  "internal_approval_start" TEXT,
  "internal_approval_end" TEXT,
  "ticket_raised_date" TEXT,
  "dn_payment_date" TEXT,
  "tat_days" TEXT,
  "civil_completion_date" TEXT,
  "hdd_length" TEXT,
  "no_of_pits" TEXT,
  "pit_ri_rate" TEXT,
  "proj_savings_per_dn" TEXT,
  "surface_wise_length" TEXT,
  "road_name" TEXT,
  "permission_receipt_date" TEXT,
  "permit_no" TEXT,
  "permit_start_date" TEXT,
  "permit_end_date" TEXT,
  "permitted_length_by_ward_mts" TEXT
);
DROP TABLE IF EXISTS "po_master" CASCADE;
CREATE TABLE "po_master" (
  "id" BIGSERIAL PRIMARY KEY,
  "route_id_site_id" TEXT,
  "parent_route" TEXT,
  "route_type" TEXT,
  "uid" TEXT,
  "po_no_cobuild" TEXT,
  "po_length_cobuild" TEXT,
  "po_no_ip1" TEXT,
  "po_length_ip1" TEXT,
  "route_routelm_metrolm_lmcstandalone" TEXT
);
DROP TABLE IF EXISTS "master_tracker" CASCADE;
CREATE TABLE "master_tracker" (
  "id" BIGSERIAL PRIMARY KEY,
    "source_id" TEXT,
"dn_number" TEXT,
  "circle" TEXT,
  "state" TEXT,
  "city" TEXT,
  "area" TEXT,
  "type_of_build" TEXT,
  "financial_year" TEXT,
  "link_name" TEXT,
  "ce_route_id" TEXT,
  "ce_section_id" TEXT,
  "ce_subsection_id" TEXT,
  "municipal_authority" TEXT,
  "ward" TEXT,
  "road_name" TEXT,
  "start_point" TEXT,
  "end_point" TEXT,
  "authority_application_date" TEXT,
  "authority_application_number" TEXT,
  "authority_new_application_number" TEXT,
  "dn_received_date" TEXT,
  "dn_length" TEXT,
  "ri_amount" TEXT,
  "sd_amount" TEXT,
  "supervision_charge_amt" TEXT,
  "additional_charge_amt" TEXT,
  "land_length_mtrs" TEXT,
  "land_rent_start_date" TEXT,
  "land_rent_end_date" TEXT,
  "land_rent_tenure" TEXT,
  "ground_rent" TEXT,
  "access_charge" TEXT,
  "admin_charges" TEXT,
  "chamber_fee" TEXT,
  "gst" TEXT,
  "dn_amount_without_gst" TEXT,
  "dn_amount_with_gst" TEXT,
  "dn_payment_date" TEXT,
  "differential_dn_number" TEXT,
  "differential_dn_amount" TEXT,
  "differential_dn_sd" TEXT,
  "permission_receipt_date" TEXT,
  "permit_no" TEXT,
  "permit_start_date" TEXT,
  "permit_end_date" TEXT,
  "permitted_length_by_ward_mts" TEXT,
  "permitted_no_of_ducts" TEXT,
  "work_status" TEXT,
  "date_of_refund_application" TEXT,
  "refund_application_no" TEXT,
  "sd_refund_amount" TEXT,
  "sd_deductions" TEXT,
  "remarks_for_deductions" TEXT,
  "sd_check" TEXT,
  "sd_refund_date" TEXT,
  "sd_refund_ack_no" TEXT,
  "date_of_refund_application_ri" TEXT,
  "refund_application_no_ri" TEXT,
  "ri_refund_amount" TEXT,
  "penalty_deductions" TEXT,
  "remarks_for_deductions_ri" TEXT,
  "ri_refund_date" TEXT,
  "ri_refund_ack_no" TEXT
);
COMMIT;